Repository Qiskit/rustworkx, pull requests merged in 2023-02, with the labels that each got.

#787 Update PyO3 and Rust Numpy to 0.18.0
  Cargo.lock
  Cargo.toml
  src/centrality.rs
  src/connectivity/mod.rs
  src/dag_algo/mod.rs
  src/digraph.rs
  src/generators.rs
  src/graph.rs
  src/isomorphism/mod.rs
  src/layout/mod.rs
  src/matching/mod.rs
  src/random_graph.rs
  src/shortest_path/mod.rs
  src/toposort.rs
  src/traversal/mod.rs
  src/tree.rs
  src/union.rs
Labels: dependencies, automerge

#795 Move core_number to rustworkx-core
  releasenotes/notes/move-core-number-48efa7ef968b6736.yaml
  rustworkx-core/src/connectivity/core_number.rs
  rustworkx-core/src/connectivity/find_cycle.rs
  rustworkx-core/src/connectivity/mod.rs
  src/connectivity/core_number.rs
  src/connectivity/mod.rs
Labels: automerge

#820 Fix Matplotlib warning when building docs
  docs/source/tutorial/betweenness_centrality.rst
Labels: stable-backport-potential
