Repository Qiskit/rustworkx, pull requests merged in 2023-07, with the labels that each got.

#922 Pin pillow<10 in CI
  constraints.txt
Labels: automerge

#870 adding `line_graph` and `greedy_edge_color` for undirected graphs
  docs/source/api.rst
  docs/source/sources.txt
  releasenotes/notes/add-graph-greedy-edge-color-7ef35785e5768419.yaml
  rustworkx-core/src/coloring.rs
  rustworkx-core/src/lib.rs
  rustworkx-core/src/line_graph.rs
  src/coloring.rs
  src/lib.rs
  src/line_graph.rs
  tests/rustworkx_tests/graph/test_coloring.py
  tests/rustworkx_tests/graph/test_line_graph.py
Labels: automerge

#930 Adding Clippy Fix
  rustworkx-core/src/connectivity/cycle_basis.rs
Labels: stable-backport-potential

#929 Relax constraints in rustworkx-core for hashbrown and indexmap
  .github/workflows/main.yml
  rustworkx-core/Cargo.toml
Labels: automerge

#927 Reorganize API docs into subpages
  docs/source/api.rst
  docs/source/api/algorithm_functions/centrality.rst
  docs/source/api/algorithm_functions/connectivity_and_cycles.rst
  docs/source/api/algorithm_functions/dag_algorithms.rst
  docs/source/api/algorithm_functions/graph_operations.rst
  docs/source/api/algorithm_functions/index.rst
  docs/source/api/algorithm_functions/isomorphism.rst
  docs/source/api/algorithm_functions/link_analysis.rst
  docs/source/api/algorithm_functions/matching.rst
  docs/source/api/algorithm_functions/other.rst
  docs/source/api/algorithm_functions/shortest_paths.rst
  docs/source/api/algorithm_functions/traversal.rst
  docs/source/api/algorithm_functions/tree.rst
  docs/source/api/converters.rst
  docs/source/api/custom_return_types.rst
  docs/source/api/exceptions.rst
  docs/source/api/generators.rst
  docs/source/api/graph_classes.rst
  docs/source/api/index.rst
  docs/source/api/layout_functions.rst
  docs/source/api/pydigraph_api_functions.rst
  docs/source/api/pygraph_api_functions.rst
  docs/source/api/random_graph_generator_functions.rst
  docs/source/api/serialization.rst
  docs/source/index.rst
  docs/source/install.rst
Labels: stable-backport-potential, automerge

#926 Switch to Qiskit Ecosystem theme
  docs/source/_static/overrides.css
  docs/source/_templates/layout.html
  docs/source/_templates/theme_variables.jinja
  docs/source/conf.py
  docs/source/requirements.txt
Labels: stable-backport-potential, automerge

#943 Reorganize API docs into subpages (Cherry-pick of #927)
  docs/source/api.rst
  docs/source/api/algorithm_functions/centrality.rst
  docs/source/api/algorithm_functions/connectivity_and_cycles.rst
  docs/source/api/algorithm_functions/dag_algorithms.rst
  docs/source/api/algorithm_functions/graph_operations.rst
  docs/source/api/algorithm_functions/index.rst
  docs/source/api/algorithm_functions/isomorphism.rst
  docs/source/api/algorithm_functions/link_analysis.rst
  docs/source/api/algorithm_functions/matching.rst
  docs/source/api/algorithm_functions/other.rst
  docs/source/api/algorithm_functions/shortest_paths.rst
  docs/source/api/algorithm_functions/traversal.rst
  docs/source/api/algorithm_functions/tree.rst
  docs/source/api/converters.rst
  docs/source/api/custom_return_types.rst
  docs/source/api/exceptions.rst
  docs/source/api/generators.rst
  docs/source/api/graph_classes.rst
  docs/source/api/index.rst
  docs/source/api/layout_functions.rst
  docs/source/api/pydigraph_api_functions.rst
  docs/source/api/pygraph_api_functions.rst
  docs/source/api/random_graph_generator_functions.rst
  docs/source/api/serialization.rst
  docs/source/index.rst
  docs/source/install.rst
Labels: automerge

#944 Add a section to Python docs about page for rustworkx-core
  docs/source/index.rst
  rustworkx-core/README.md
Labels: documentation, stable-backport-potential, automerge
