Repository Qiskit/rustworkx, pull requests merged in 2024-06, with the labels that each got.

#1208 Move ancestors and descendants to rustworkx-core
  releasenotes/notes/ancestors-descendants-rustworkx-core-8c4aac3364c155bf.yaml
  rustworkx-core/src/traversal/mod.rs
  src/traversal/mod.rs
Labels: automerge

#1209 Move bfs_successors and bfs_predecessors to rustworkx-core
  releasenotes/notes/bfs-pred-succ-rustworkx-core-480d25a374294899.yaml
  rustworkx-core/src/traversal/mod.rs
  src/traversal/mod.rs
Labels: rustworkx-core

#1211 Rename deprecated cargo config file
  .cargo/config.toml
Labels: automerge

#1186 Move `collect_bicolor_runs()` to rustworkx-core
  releasenotes/notes/migrate-collect-bicolor-runs-ff95d7fdbc546e2e.yaml
  rustworkx-core/src/dag_algo.rs
  rustworkx-core/src/lib.rs
  src/dag_algo/mod.rs
  tests/digraph/test_collect_bicolor_runs.py
Labels: automerge, rustworkx-core

#1204 Update mpl_draw() to fix multigraph plots
  releasenotes/notes/fix-mpl-draw-digraph-plots-aecf86738ab9b0db.yaml
  rustworkx/visualization/matplotlib.py
Labels: automerge

#1203 Potential fix to the tooltip with special characters bug
  releasenotes/notes/fix-graphviz-draw-tooltip-3f697d71c4b79e60.yaml
  src/dot_utils.rs
  tests/digraph/test_dot.py
  tests/graph/test_dot.py
  tests/visualization/test_graphviz.py
Labels: automerge

#1217 Fix Clippy warnings due to 1.79
  rustworkx-core/src/connectivity/biconnected.rs
  rustworkx-core/src/connectivity/chain.rs
  rustworkx-core/src/generators/random_graph.rs
  rustworkx-core/src/planar/lr_planar.rs
  rustworkx-core/src/steiner_tree.rs
  src/connectivity/johnson_simple_cycles.rs
  src/iterators.rs
  src/layout/spring.rs
  src/random_graph.rs
  src/shortest_path/floyd_warshall.rs
  src/shortest_path/mod.rs
Labels: automerge

#1215 Add `is_semi_connected()` to `rustworkx`
  releasenotes/notes/is-semi-connected-d4176b228aa62baf.yaml
  rustworkx/__init__.pyi
  rustworkx/rustworkx.pyi
  src/connectivity/mod.rs
  src/lib.rs
  tests/digraph/test_is_semi_connected.py
Labels: automerge

#1091 Add functions to parse node link JSON
  docs/source/api/serialization.rst
  releasenotes/notes/add-node-link-json-parse-ef74e5b0d97c0941.yaml
  rustworkx/__init__.pyi
  rustworkx/rustworkx.pyi
  src/json/mod.rs
  src/json/node_link_data.rs
  src/lib.rs
  tests/digraph/test_node_link_json.py
  tests/graph/test_node_link_json.py
Labels: automerge

#1221 Remove SciPy as a development dependency
  .github/workflows/main.yml
  noxfile.py
  tests/digraph/test_hits.py
  tests/digraph/test_pagerank.py
  tox.ini
Labels: automerge

#1089 compute maximum bisimulation using Paige-Tarjan's Algorithm
  releasenotes/notes/maximum-bisimulation-942a9d0dc9b46ee4.yaml
  rustworkx/__init__.pyi
  rustworkx/rustworkx.pyi
  src/bisimulation.rs
  src/iterators.rs
  src/lib.rs
  tests/digraph/test_bisimulation.py
Labels: automerge

#1223 Subtle name change for `with_capacity` hints
  releasenotes/notes/with-capacity-6f35d43e256e268e.yaml
  rustworkx/rustworkx.pyi
  src/digraph.rs
  src/graph.rs
  tests/digraph/test_pickle.py
  tests/graph/test_pickle.py
Labels: automerge

#1213 Add `periodic` to `hexagonal_lattice_graph`
  rustworkx-core/src/generators/hexagonal_lattice_graph.rs
  rustworkx-core/src/generators/mod.rs
  rustworkx/generators/__init__.pyi
  src/generators.rs
  tests/generators/test_hexagonal.py
  tests/visualization/test_mpl.py
Labels: automerge

#1194 Add `layers` function to `rustworkx-core`
  releasenotes/notes/add-layers-rustworkx-core-1caaccb1ca292ca8.yaml
  rustworkx-core/src/dag_algo.rs
  rustworkx-core/src/err.rs
  src/dag_algo/mod.rs
Labels: rustworkx-core

#1234 Bump version strings post release
  Cargo.lock
  Cargo.toml
  docs/source/conf.py
  setup.py
Labels: automerge
