Repository Qiskit/rustworkx, pull requests merged in 2024-02, with the labels that each got.

#1084 Improve ergonomics of `tox` lint jobs
  pyproject.toml
  tox.ini
Labels: automerge

#1096 Improve performance of custom-iterator `__getitem__`
  src/iterators.rs
Labels: stable-backport-potential

#1101 Fix backport branch post 0.14.0 release
  .mergify.yml
Labels: automerge

#1109 Add missing musl skip for ppc64le builds
  .github/workflows/wheels.yml
Labels: stable-backport-potential, automerge

#1120 Reorder and tweak README.md sections
  README.md
Labels: automerge
